title: Cornerstone Insurance
description: > # this means to ignore newlines until "show_excerpts:"
  Cornerstone Insurance provides comprehensive insurance solutions including life, health, 
  trauma, income protection, and mortgage protection. Secure your future with our trusted 
  insurance expertise and personalized coverage options.
url: 'https://www.cornerstonefs.co.nz' # Your actual domain
baseurl: ''

plugins:
  - jekyll-feed
  # - jekyll-sitemap  # Disabled - using custom sitemap.xml with hreflang support instead
  # - jekyll-minifier  # Disabled - using terser/cssnano for better minification

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  posts_zh:
    output: true
    permalink: "/blog/:title/"
  posts_en:
    output: true
    permalink: "/en/blog/:title/"
  pages:
    output: true

# jekyll-minifier disabled - using modern terser/cssnano instead
# jekyll-minifier:
#   uglifier_args:
#     harmony: true

# HTML Compression (Phase 1 optimization for text-HTML ratio)
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  ignore:
    envs: [development]


twitter:
  card: summary_large_image

# SEO and Social Media
author: "Cornerstone Insurance"
logo: "/assets/img/logo.svg"
social:
  name: "Cornerstone Insurance"
  links:
    - "https://www.cornerstonefs.co.nz"

# Additional SEO settings and i18n
lang: zh-CN
default_lang: zh
languages: ["zh", "en"]
timezone: Pacific/Auckland

# Chinese SEO optimization
chinese_seo:
  baidu_site_verification: # Add your Baidu verification code here
  sogou_site_verification: # Add your Sogou verification code here
  bing_site_verification: # Add your Bing verification code here
  google_site_verification: # Add your Google verification code here

# Global SEO defaults
seo:
  default_image: "/assets/img/hero-bg.jpg"
  image_alt: "Cornerstone Insurance hero background"
  chinese_keywords: "新西兰保险,华人保险顾问,奥克兰保险,人寿保险,健康保险,重大疾病保险,收入保障保险,房贷保护保险,FSP持牌,保险理赔,Amy保险顾问"
  location_keywords: "奥克兰,新西兰,惠灵顿,基督城,汉密尔顿,华人社区,新西兰华人"

# i18n settings
t:
  zh:
    site:
      title: "Cornerstone Insurance"
      description: "Cornerstone Insurance提供全面的保险解决方案，包括人寿保险、健康保险、重大疾病保险、收入保障保险和房贷保护保险。通过我们值得信赖的保险专业知识和个性化保障选择，为您的未来保驾护航。"
  en:
    site:
      title: "Cornerstone Insurance"
      description: "Cornerstone Insurance provides comprehensive insurance solutions including life, health, trauma, income protection, and mortgage protection. Secure your future with our trusted insurance expertise and personalized coverage options."

include:
  - _redirects

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor
  - BUILD.md
