title: Cornerstone Insurance
description: > # this means to ignore newlines until "show_excerpts:"
  Cornerstone Insurance provides comprehensive insurance solutions including life, health, 
  trauma, income protection, and mortgage protection. Secure your future with our trusted 
  insurance expertise and personalized coverage options.
url: 'https://www.cornerstonefs.co.nz' # Your actual domain
baseurl: ''

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/blog/:title/"
  pages:
    output: true

jekyll-minifier:
  uglifier_args:
    harmony: true


twitter:
  card: summary_large_image

# SEO and Social Media
author: "Cornerstone Insurance"
logo: "/assets/img/logo.svg"
social:
  name: "Cornerstone Insurance"
  links:
    - "https://www.cornerstonefs.co.nz"

# Additional SEO settings and i18n
lang: zh-CN
default_lang: zh
languages: ["zh", "en"]
timezone: Pacific/Auckland

# Global SEO defaults
seo:
  default_image: "/assets/img/hero-bg.jpg"
  image_alt: "Cornerstone Insurance hero background"

# i18n settings
t:
  zh:
    site:
      title: "Cornerstone Insurance"
      description: "Cornerstone Insurance提供全面的保险解决方案，包括人寿保险、健康保险、重大疾病保险、收入保障保险和房贷保护保险。通过我们值得信赖的保险专业知识和个性化保障选择，为您的未来保驾护航。"
  en:
    site:
      title: "Cornerstone Insurance"
      description: "Cornerstone Insurance provides comprehensive insurance solutions including life, health, trauma, income protection, and mortgage protection. Secure your future with our trusted insurance expertise and personalized coverage options."

include:
  - _redirects

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor
