[build]
  command = "npm run build:prod"

[context.production.environment]
  JEKYLL_ENV = "production"
  NODE_VERSION = "18"

[context.branch-deploy.environment]
  JEKYLL_ENV = "staging"
  NODE_VERSION = "18"

[context.deploy-preview.environment]
  JEKYLL_ENV = "staging"
  NODE_VERSION = "18"

# Redirect rules to handle double trailing slash issues for English pages
[[redirects]]
  from = "/en/faq//"
  to = "/en/faq/"
  status = 301

[[redirects]]
  from = "/en/services//"
  to = "/en/services/"
  status = 301

[[redirects]]
  from = "/en/team//"
  to = "/en/team/"
  status = 301

[[redirects]]
  from = "/en/blog//"
  to = "/en/blog/"
  status = 301

[[redirects]]
  from = "/en/contact-us//"
  to = "/en/contact-us/"
  status = 301

[[redirects]]
  from = "/en/about//"
  to = "/en/about/"
  status = 301

[[redirects]]
  from = "/en/glossary//"
  to = "/en/glossary/"
  status = 301

[[redirects]]
  from = "/en/calculators//"
  to = "/en/calculators/"
  status = 301

[[redirects]]
  from = "/en/disclosure//"
  to = "/en/disclosure/"
  status = 301

[[redirects]]
  from = "/en/privacy-policy//"
  to = "/en/privacy-policy/"
  status = 301

[[redirects]]
  from = "/en/terms//"
  to = "/en/terms/"
  status = 301
